# Generated by Django 3.0.7 on 2020-12-27 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20201227_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='designation_name',
            new_name='designation',
        ),
    ]
